extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - react-app
rules:
  "@typescript-eslint/explicit-module-boundary-types": error
  "@typescript-eslint/no-unused-vars": error
  react-hooks/exhaustive-deps: error
