[package]
name = "core-wasm"
version = "1.0.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
once_cell = "1.7.2"
rand = { version = "0.7.3", features = ["wasm-bindgen"] }
wasm-bindgen = "0.2.73"
