name: Test
on:
  push:
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: rustup target add wasm32-unknown-unknown
      - run: cargo build --release --target wasm32-unknown-unknown
        working-directory: packages/core-wasm

      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install -g npm@7
      - run: npm ci

      - run: cargo test
        working-directory: packages/core-wasm

      - run: npm test
      - run: npm test --workspaces
